### ISSUE TITLE
Suspended tabs are duplicated when firefox starts

### ISSUE THREAD

**Issue by JosephCaillet** [rNeomy/tab-suspender#1]
I started Firefox (without any suspended tabs), and I choose to suspend one :
![1 _before_restart](https://cloud.githubusercontent.com/assets/10532348/21548940/77375984-cdef-11e6-9983-74694e5e88f0.PNG)
I closed Firefox, and when I started it again, suspended tab where duplicated :
![2_first_restart](https://cloud.githubusercontent.com/assets/10532348/21548941/777247ec-cdef-11e6-939c-2541e7b366fb.PNG)
And if I close Firefox again, and start it again, suspended tab  duplicates again :
![3_second_restart](https://cloud.githubusercontent.com/assets/10532348/21548942/7775287c-cdef-11e6-92b4-6de8b286568d.PNG)
This is very annoying, as I often have more than 10 suspended tabs, closing all the duplicates tabs at each Firefox start-up is very annoying.

**Comment by rNeomy** [comment]
There is a new option in the options page to turn session restore on and off. For Firefox and Opera browsers this option will be off by default.

Thanks for the report. This should have been fixed on 0.1.5
