### ISSUE TITLE
coffee favicon - option to turn off

### ISSUE THREAD

**Issue by Paul00777** [rNeomy/tab-suspender#2]
Hi
Thank you for the great extension. It's helping cut down on both my firefox cpu usage and memory.
Please can we have an option to turn off the coffee cup favicon. I have 7 pinned tabs and I am unable now to see what is what. I would prefer to not know if the tab is suspended, or have the tab background coloured.
regards,
Paul

**Comment by rNeomy** [comment]
Chrome screenshot.
![screen shot 2017-01-13 at 11 45 19](https://cloud.githubusercontent.com/assets/14104614/21922822/c7c0862c-d985-11e6-8580-5e6160c3a552.png)

This is Firefox only issue. Basically Firefox still does not support `chrome://favicon/` API yet. So basically the extension is not able to retrieve the fav icon and display it properly. That's the reason why the default coffee icon is shown.

Note that WebExtension context is very limited in term of accessing low level APIs, so we need to wait until this API is supported.

**Comment by Paul00777** [comment]
Thank you for taking the time to reply.

**Comment by zsection** [comment]
Thanks for letting us know. Unfortunately I can't use the addon until this is resolved. Will check in again soon

**Comment by ajostergaard** [comment]
Opera FTW. ;)
