### ISSUE TITLE
Chrome/Opera: Extension crashes in incognito/private mode

### ISSUE THREAD

**Issue by mxyzplx** [rNeomy/tab-suspender#20]
Does tab suspender not work in incognito mode for Chrome and private window mode for Opera? 

It DOES work for Firefox in private mode. However, on those Chromium-based browsers, when in private mode and tab suspender is activated, the page just crashes and a warning appears saying that the extension was blocked by an extension, "Try disabling your extensions."

I've done that, on a new installation of Opera with only Tab Suspender enabled. Opened a private window, tried to suspend a tab, and it still says that some extension is blocking tab suspender -- even though tab suspender is the only extension enabled.
![screenshot from 2017-04-28 17-56-37](https://cloud.githubusercontent.com/assets/18336165/25548764/0c454374-2c3c-11e7-9300-0ab8e386110f.png)
If it's not meant to function in Chrome/Opera private windows, that's fine. I just didn't see any information stating that.

(Oh, and if you just click the browser back button, you go back to the page that failed to suspend. So in a weird way, the typical suspend action and the crash achieve the same end, just through different means.)

**Comment by rNeomy** [comment]
This is fixed per https://add0n.com/tab-suspender.html#comment-3414531797. Thanks for the report.
