### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by v-dawg** [rNeomy/tab-suspender#24]
- thumbnail off the suspended website
- compatible with themes ( it always uses the standard tab appearance for the suspended tabs)

**Comment by rNeomy** [comment]
> compatible with themes ( it always uses the standard tab appearance for the suspended tabs)

Can you explain more?

**Comment by IdmFoundInHim** [comment]
If possible, make the suspended page use `color.ntp_background` and `color.ntp_text` from the [WebExtensions theme Object](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme#colors)
