### ISSUE TITLE
Tab Suspender breaks bookmarking of unloaded tabs

### ISSUE THREAD

**Issue by leedoyle** [rNeomy/tab-suspender#27]
When you bookmark all tabs and there are unloaded tabs among them, or when you bookmark unloaded tabs using multiple tab handler, those will be bookmarked with URLs like this: 

> moz-extension://094a6e04-0d3d-4ec6/data/suspend/index.html?title=NameofthePage&url=https%3A//en.wikipedia.org/wiki/Articlename&favicon=https%3A//en.wikipedia.org/static/favicon/wikipedia.ico.

That means these bookmarks won't work in a different browser/profile without Tab Unloader installed, and I'm not sure if they will work without Tab Unloader database.
The same applies to saving browser sessions.

It would be great if Tab Suspender offered functionality to mitigate the issue, for instance by cleaning URLs of recent bookmarks or interfering with the process of adding bookmarks and preventing its data from getting into bookmark URLs. 
Right now I can only think of using a third party tool to open such bookmarks, e.g. Redirector. 

Another option would be to add a disclaimer clarifying the issue for new users.

**Comment by tonsimple** [comment]
yep, also confirming this 

P.S.:
@leedoyle 
As a quick and dirty workaround, you can discern the original URL there, slightly mauled.
Just in case you're trying to fix some bookmarks or anything

**Comment by rNeomy** [comment]
There is a way to observe bookmark events and fix the URL when an internal page is bookmarked. This is what I did in 081feb705928de0b63ce37ba63186cd4521ab413. However, there is a problem with this method. When you click on the star button to bookmark the tab, it does not keep the yellow color as the URL is changed and hence the old URL (the internal one) is not in the bookmark database anymore. This might be confusing to users. Please give the master branch a try and let me know if we need to improve this somehow.

If you have problem installing the master branch let me know to provide more info.

**Comment by rayman89** [comment]
I think the star on the url thing will be easily deducted when the user loads the normal url and sees it. But if you want to be extra sure you can create a notification that says your bookmark was saved correctly.

**Comment by rNeomy** [comment]
fixed on 0.1.9; https://addons.mozilla.org/en-US/firefox/addon/tab-suspender-tab-unloader/versions/beta

**Comment by DucthBillyMac** [comment]
hi, first time here.  hope doing this in the right place.  i've done some lo-medium vba for excel & strength in product review, tech writing, upgrade requests, some programming.  i have some interest in the apps for addons to firefox.  i've only briefly read the procedures & don't quite get but :)  been up 48 hours & trying to fix a couple of things before upgrades..  site master:  i would be able to reduce your "hello world" procedural page from 40:1 but yep it's more work, a faster read & everyone gets things done faster.  

for here the best i can do now is give copy of my review what working on where a couple of things apply else out of gas now for the rest.  pardon copy of my notes (self explanatory)

==========

- IN SOME ORDER OF IMPORTANCE (found links to some fair matches)

CLOSE ALL TABS BUTTON      https://addons.mozilla.org/en-US/firefox/extensions/
  NEED:  NEW WINDOW OPEN 1ST TAB AS BLANK & PINNED (will compliment close all tabs button; minor step for do 1 window but anways..)

GET AUTO CLOSE 1 BAD TAB
GET RECOVER ALL TABS FROM LAST SESSION  (saw an example)
GET ON CRASH (or other settings) CLOSE FFOX, TERMINATE PROCESS, SO CAN CLEAR RAM & TEMP FILES (CCLEANER AND/OR RAM OTHER) RESTART FF, RECOVER LAST SESSION

TAB SUSPENDER:		   https://addons.mozilla.org/en-US/firefox/addon/tab-suspender-tab-unloader/?src=search
  https://add0n.com/tab-suspender.html?version=0.1.8&type=install

  DO NOT SEE A PMODE STATUS:
HOW TELL IN PRIVACY MODE:  (not working, with theme addon: brushed-metal-xp), CNTRL-SHIFT-P  see a Mask icon on the top left corner (NOT SEEING THAT).
  PRIVACY TAB 0.2.2 is legacy tech has access to all browser functions for permissions,  private:  put:  private:infrontofaddress.com (tab names have dotted lines?)   
	https://addons.mozilla.org/en-US/firefox/addon/private-tab/
  srch goog:  firefox how tell if in privacy mode with brushed-metal-xp

HIDE BOTH TAB & NAV BARS, ck F11:   look for rc, navigation toolbar checkmark (old set? not exist on mine)  https://support.mozilla.org/en-US/questions/995349
  for hide just 1 window, both bars?  	https://support.mozilla.org/en-US/questions/995349
-----


SECONDARY:
GET HORIZ BAR DISAPEAR TOOL
GET RID OF STAR IN LINKS ICON (never use the bookmark this page for show your bookmarks; takes up space, else change star to have option use:  bookmark all)
HIDE MY IP (VPN's CK):	   https://addons.mozilla.org/en-US/firefox/search/?q=hide&appver=&platform=windows

HOW SAVE ALL TO TRANSFER SETTINGS: checking

RAM CK
