### ISSUE TITLE
Automatic suspend 

### ISSUE THREAD

**Issue by dyiliq** [rNeomy/tab-suspender#3]
Automatic suspend tabs after x number of open tabs.

**Comment by rNeomy** [comment]
Thanks for the suggestion. The latest dev version has a new option. Basically two conditions need to be met for a tab to be suspended. 1. Timeout 2. Number of open tabs.

To have what you are looking for, you can decrease the timeout to 1 minute and then when  both conditions are met, tab will suspend.

You can give the dev version a try and report bugs. Let me know if you need help installing the dev version.
