### ISSUE TITLE
Option "Automatically suspend tabs after" conflicts with documentation on Firefox 55.0.3, Windows 7

### ISSUE THREAD

**Issue by tyxchen** [rNeomy/tab-suspender#37]
The option "Automatically suspend tabs after (in minutes)" sets a minimum value of 5. However, according to the documentation provided as a footnote, the minimum value for the input is 1.

Steps to reproduce:
1. Go to the addons entry in about:addons and scroll to the options
2. Set the "Automatically suspend tabs after" option to a number from 1 to 5 (e.g. 2)

Expected:
According to the documentation in the footnote, the option should be valid.

Actual:
The option is visually marked as being invalid, and hovering over the input produces the message "Please select a value that is no less than 5."

**Comment by jbwyatt4** [comment]
Can confirm! On Ubuntu.
