### ISSUE TITLE
Can we unsuspend on enter or space?

### ISSUE THREAD

**Issue by stites** [rNeomy/tab-suspender#38]
I noticed that the homepage says that features include: "Unload all tabs per user action." I don't see this user action in the settings, though.

As a feature request: is it possible to unload one tab via a user action? Coming from Chrome's "Ultimate Suspender" I'm used to hitting enter or space on a page and getting the page back.

**Comment by WolfganP** [comment]
I was going to request the same feature, the ability to manually unload/suspend a particular tab (ie right click on the tab name at the top or the tab entry on the tab list V)

**Comment by stites** [comment]
Looks like it might just be a c/p job with [data/suspend/index.js#L86](https://github.com/rNeomy/tab-suspender/blob/master/data/suspend/index.js#L86).

**Comment by rNeomy** [comment]
We have an option to automatically unsuspend tab when gain focus. Will have both "Space" and "Enter" as the unsuspend event on the next release.

**Comment by rNeomy** [comment]
"Enter", "Space" and "Esc" are now supported
