### ISSUE TITLE
Spelling error on suspended page view.

### ISSUE THREAD

**Issue by sanitybit** [rNeomy/tab-suspender#4]
> DoubleClick anywhere to unsunsend this Tab 

Should read:

Double-click anywhere to unsuspend this tab. 

Although it is my opinion that there may be [better choices](http://english.stackexchange.com/questions/44961/antonym-of-suspend-as-in-suspend-a-user-account) than unsuspend (e.g. reactivate).

**Comment by rNeomy** [comment]
Thanks will be fixed on the next release
