### ISSUE TITLE
Remove suspended page from History

### ISSUE THREAD

**Issue by TitanNano** [rNeomy/tab-suspender#40]
Right now the addon creates a new history entry each time a tab is suspended.

This two hacks can prevent this:

1. Do the suspending from inside the content script with `location.replace(...)` so the current tab history won't be extended. When restoring the tab, also use `location.replace(...)` to restore the previous page.

2. Use something like this snippet after suspending and restoring:
```JavaScript
browser.history.search({ text: '7df3bb56-9ecd-a149-9a5c-fdf7149a56e9' })
    .then(results => {
        console.log(results);
        return Promise.all(results.map(item => browser.history.deleteUrl({ url: item.url })));
    }).then(results => console.log(results));
```
This removes all traces of the addon from the general browser history.

**Comment by forteller** [comment]
Yes please! It's so annoying to go back in history only to get back to the "suspended" page.

Otherwise: Thanks for a great extension!

**Comment by rNeomy** [comment]
Having suspended tabs on the history list is important for restoring them instead of creating.
https://github.com/rNeomy/tab-suspender/issues/21

**Comment by brunoais** [comment]
@rNeomy But do you need it after the tab is unsuspended?

**Comment by HamidZaeri** [comment]
Why not use a two action (button) in the suspended page, one which reloads the page and one to do go back to the original page in history?

**Comment by ardiefox** [comment]
Adding an option to let users choose to restore or refresh might be great. In my case, I prefer refreshing, because every time I unsuspend a tab I hit Reload button to fetch the latest version of the web page.

**Comment by rNeomy** [comment]
Okay then, now Tab Suspender uses "history.back()" whenever possible which restores tab state. You can ask to refresh the tab instead using the new entry in the options page.

> But do you need it after the tab is unsuspended?

So there will be no history on the default settings

Try the dev version and report if it is not working as expected.
