### ISSUE TITLE
Option to remove the button from address bar and context menu

### ISSUE THREAD

**Issue by forteller** [rNeomy/tab-suspender#41]
Hi. Thanks for this great extension! I've been using it for a long time and is very pleased with it.

One thing I would prefer if you could add, though:

I never use the t-button in the address bar or the "Suspend this tab" in the context menu. All I want is for the extension to suspend tabs automatically after some time. I would love it if you could add options to not show these.

In the address bar the t "blinks" in and out of existence every time the address changes, and with it moves all the other icons in the bar. [Scroll down this page](https://discuss.flarum.org/d/6341-flarum-v0-1-0-beta-7-released) to notice how annoying that can be. In addition the small, blue t looks very much out of place among the slightly larger, gray icons.

The context menu is less annoying, but I never use it and I already have a ton of things in the context menu, so every time I want to use something in it I have to spend extra time looking for it among all the options there.

Thanks again for your work!

**Comment by HamidZaeri** [comment]
yeah, me too. it's good to disable both of them

**Comment by HamidZaeri** [comment]
The context menu option does not apply to tab context menu?!

**Comment by rNeomy** [comment]
Tab context is barely used. Do we need to removed the items from there too?
