### ISSUE TITLE
Suspended & pinned tabs are restored unpinned

### ISSUE THREAD

**Issue by aurelg** [rNeomy/tab-suspender#43]
I've set the `When Firefox Developer Edition starts` to `Show your windows and tabs from last time`. On close, some of my tabs are pinned and suspended. On restart, though, pinned tabs that were suspended now appear unpinned. I would expect them to stay pinned.

Config:
- Firefox Developer Edition 57.0b4 (64-bit)
- Tab Suspender 0.1.8

**Comment by perdolka** [comment]
Same here.
FF version - 55.0.3 (x64)
Maybe conflict with "Tree Style Tab" ?
