### ISSUE TITLE
don't start background tabs at all, until focused

### ISSUE THREAD

**Issue by filbo** [rNeomy/tab-suspender#5]
Hi,

I'm looking for an even firmer version of what #3 asks for.  Any time I open a tab in the background, I want the visual appearance of the tab, but the browser shouldn't even _fork_ until I eventually give focus to that tab.  I don't want it to create the DOM, access the web site, do all that work, _then_ be suspended by you a minute later; I want you to **create** it in the suspended state.  (Helpful context: it is not unusual for me to look at a list of, let's say articles on The Register, but it could be notifications on Facebook, or whatever -- and Ctrl-Click 20 of them in rapid succession.  Could be 20 background tabs created in 15 seconds.  With proper tab handling [as was lamentably last seen in Opera 12], this should happen in realtime without the slightest hint of lag in any aspect of the UI.  20 new segments appear in the tab bar, 20 favicons wink on in rapid succession, everything should be totally smooth...)

I'm using Opera, occasionally Chrome if an Opera version is troublesome.  Current Opera (Developer) can be configured so that at startup time, tabs of the prior session are loaded in this sort of incipient state.  e.g. if tabs 1, 2, 3, 4 existed, 2 was focused, and I restarted the browser, then tab 2 would come up fully, while tabs 1, 3, 4 are waiting to be activated.  But there is no Opera setting to say "furthermore, any _new_ tabs I create in the background should also be quiescent like that".  So I'm hoping you can provide it.

Ideally, of course, the implementation would cause them to enter *Opera's* quiescent state, rather than having a second one which will probably interact weirdly with things like: open in background tab (5), now tab 5 is in tab-suspender-quiescent state; exit Opera; start Opera; what state is tab 5 in now?

This should be an additional option orthogonal to the timer and #tabs options.  Once I have activated (focused) a tab once (and then defocused), _then_ it should be subject to the timer (though I expect I'll leave that disabled).

**Comment by rNeomy** [comment]
So in the next version, it would be possible to open tabs in suspend mode from the right click context menu over links.
