### ISSUE TITLE
request - grey title of tab

### ISSUE THREAD

**Issue by perdolka** [rNeomy/tab-suspender#50]
Grey-shaded text of suspended tabs, like in BarTab

**Comment by rNeomy** [comment]
as far as I know it is not possible to change the tab style with WebExtensions. If you have a sample extension that does this please reopen

**Comment by perdolka** [comment]
> it is not possible to change the tab style with WebExtensions
Yep, you're right.

I know only one way - 
user_profile/chrome/userChrome.css

.tabbrowser-tab[pending] 
{
opacity: .5;
}
