### ISSUE TITLE
CTRL-click on Tabs to suspend

### ISSUE THREAD

**Issue by Froghut** [rNeomy/tab-suspender#52]
As the title says it would be great if you could add a "shortcut" to suspend tabs by holding a configurable modifier key and just click on a tab.

**Comment by yfdyh000** [comment]
[Bug 1246706 Allow listening for mouse events on tabs RESOLVED WONTFIX](https://bugzilla.mozilla.org/show_bug.cgi?id=1246706).

**Comment by rNeomy** [comment]
It is not possible in Chrome either.

**Comment by Froghut** [comment]
Sad to hear, but thanks for the info!
