### ISSUE TITLE
Single click to restore tab?

### ISSUE THREAD

**Issue by TimMensch** [rNeomy/tab-suspender#6]
Feature Request:

I've been using the "Great Suspender" on Chrome, but found this for Firefox. Now switching between Chrome and Firefox is a pain, because I click once to resume a tab on Chrome and double-click in Firefox.

I prefer the single-click, and don't see why a double-click should be required. Any chance of adding an option to listen for single click?

**Comment by rNeomy** [comment]
Have you tried automatic resume? If the option is checked, when a page is active, it will automaticity resumes.

**Comment by TimMensch** [comment]
I don't want automatic resume, though. I want to be able to flip through pages to see what they are and then select one to bring up.

**Comment by ajostergaard** [comment]
The second click does seem redundant, unless single click does something I haven't noticed?
