### ISSUE TITLE
restore not working

### ISSUE THREAD

**Issue by ericdkaufman** [rNeomy/tab-suspender#7]
I have a series of tabs where the url looks similar to the following:

moz-extension://f163436d-3cc7-5341-9070-be00c54122d5/data/suspend/index.html?title=http%3A//www.canonrumors.com/&url=http%3A//www.canonrumors.com/

I cannot get them to restore. I have tried to unsuspend all tabs, single clicking and double clicking, etc. I cannot seem to get them back. I am running Firefox 51.0.1 on Mac OSX 10.11.6.

**Comment by rNeomy** [comment]
Go to the extension's option page and turn session restore on. By default in Firefox this option is off.

**Comment by cwre** [comment]
@rNeomy how do you turn on session restore in the extension option page? I see no radio button to turn it on, and the blank box underneath gives no hints as to the appropriate method for enabling this feature.

**Comment by cwre** [comment]
Picture's worth a thousand words:

<img width="1044" alt="screen shot 2017-03-20 at 10 52 34 am" src="https://cloud.githubusercontent.com/assets/6749810/24105477/5ea45a74-0d5b-11e7-99eb-b7c7bd9199f5.png">

**Comment by rNeomy** [comment]
This was a Firefox bug, right? It should have fixed itself. Please reopen if not.
