### ISSUE TITLE
Tabsuspender looses tabs

### ISSUE THREAD

**Issue by a-pirard** [rNeomy/tab-suspender#8]
Nice program! But...
I was using Tabsuspender 1.5 with FF 51.0.1 (64-bit) on Ubuntu 12.4.
I use many pages and tabs.
I upgraded to 1.6.
When I restarted FF, all focused tabs had disappeared.
Fortunately, I found I could restore History>Recently Closed Tabs on each page.

When using 1.5, I found New Tabs that were empty and should not.
One of them restored its contents when I created a tab to the left of it.
Another one when I restarted Firefox.
But other tab suspenders might have had the same problem.
Sorry if this one is fuzzy and uncertain in my mind.
But watch out.

**Comment by rNeomy** [comment]
In Firefox, you need to enable session restore from options page. By default it is disabled since Firefox's built-in session restore also restore 'chrome://' tabs.

**Comment by a-pirard** [comment]
On 2017-03-16 09:23, rNeomy wrote:
>
> In Firefox, you need to enable session restore from options page. By
> default it is disabled since Firefox's built-in session restore also
> restore 'chrome://' tabs.
>
I'm afraid that you are very unclear.
Do you mean a preference in Edit>Preferences>General?
>General>When Firefox starts>Show my windows and tabs from last time maybe?
I do have that option turned on.
And it normally should not affect disabling Tab Suspender.
You should close bugs only when they are solved.

I saw Tab Suspender closes all focused tabs when it gets disabled or
when Firefox is restarted.
They can be restored one by one with History>Recently Closed Tabs
But when TS is disabled, tabs cannot be restored (because the required
moz-extension is no longer available).
That's sorry because it's a good program.

**Comment by rNeomy** [comment]
From version 0.1.8, there is no option for restoring tabs. The extension does restore all the suspended tabs with a few second delay. Please wait for 0.1.8 to get reviewed and reopen if you sill have this issue.
