### ISSUE TITLE
Auto Tab Discard

### ISSUE THREAD

**Issue by rayman89** [rNeomy/tab-suspender#85]
Sorry if this is not the place but since I did not find a github for Auto Tab Discard I'm posting here my request.

Could you add to the tab context menu the ability to unload that tab and the ability to whitelist the domain of that tab please? Thank you.

**Comment by rNeomy** [comment]
done. thanks for the suggestions! we now have the GitHub page; https://github.com/rNeomy/auto-tab-discard

**Comment by rayman89** [comment]
Thank you for implementing it.
