### ISSUE TITLE
Options page opens in existing tab

### ISSUE THREAD

**Issue by ajostergaard** [rNeomy/tab-suspender#9]
When I right click on the tab-suspender 't' and select Options the page opens in a pre-existing tab. It should open a new tab and not obscure one of mine.

Opera 43.0.2442.1144

Great plugin btw, couldn't have switched from Chrome without it. :)

**Comment by rNeomy** [comment]
Thanks for the report. Unfortunetly there is no fix for this. We call internal API and the API handles this; https://github.com/rNeomy/tab-suspender/blob/master/common.js#L221
